#!/usr/bin/env bash
# config file for SSL certificate

DOMAIN="haroldo.tech"
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get -y install certbot
sudo mkdir -p /etc/haproxy/ssl
sudo chmod -R go-rwx /etc/haproxy/ssl
cd /etc/haproxy/ssl && certbot certonly --standalone
cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/ssl/$DOMAIN.pem
