#!/usr/bin/env bash
# transfers a file from our client to a server

if [ $# -gt 2 ]; then
    if [ $# -eq 4 ]; then
	scp -i "$4" "$1" "$3@$2":~/
    else
	scp "$1" "$3@$2":~/
    fi
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
