#!/usr/bin/env bash
# redirect with 301

cp sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/haroldo.tech
new_string="server_name haroldo.tech\nrewrite ^/$ https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sed -i "s/server_name _/$new_string/" /etc/nginx/sites-available/haroldo.tech
