#!/usr/bin/env bash
# redirect with 301

sudo apt-get update
sudo apt-get -y install nginx
#sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/haroldo.tech
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
cd /etc/nginx/sites-available
sudo sed -i "s/server_name _;/$new_string/" default
#sudo sed -i "s/listen 80 default_server;/listen 80;/" haroldo.tech
#sudo sed -i "s/listen \[::\]:80 default_server;/listen [::]:80;/" haroldo.tech
#sudo ln -fs /etc/nginx/sites-available/haroldo.tech /etc/nginx/sites-enabled/
sudo service nginx start
